library(dplyr)
library(Seurat)
options(warn=-1)
pbmc.data <- Read10X(data.dir="/Users/yuliangwang/Desktop/GSE155585_RAW/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "GCB1_filtered", min.cells = 3, min.features = 200)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^mt-")
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3,pt.size = 0)
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 20)
pbmc <- NormalizeData(pbmc)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000, verbose=F)
VariableFeaturePlot(pbmc)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes, verbose=F)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc), verbose=F)
ElbowPlot(pbmc,ndims = 50)
pbmc <- FindNeighbors(pbmc, dims = 1:15, verbose=F)
pbmc <- FindClusters(pbmc, resolution = 0.6, verbose=F)
VlnPlot(pbmc,features = c("Tle3","Hhex","Cd38","Ccr6","Myc","Irf4"),pt.size = 0)
pbmc <- RunTSNE(pbmc, dims = 1:15)
DimPlot(pbmc, reduction = "tsne")
FeaturePlot(pbmc,features = c("Cxcr4","Cd83","Cd86","Mki67"),label = TRUE)
new.cluster.ids <- c("LZ", "DZ", "DZ", "LZ", "DZ", "DZ", 
                     "LZ", "Myc_cellcyle", "Myc_plasma","Pre_Memory_B_cells")
names(new.cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, new.cluster.ids)
DimPlot(pbmc, reduction = "tsne", label = TRUE, pt.size = 0.5) + NoLegend()
pbmc.markers<-FindAllMarkers(pbmc,only.pos = TRUE)
write.table(pbmc.markers,file = "/Users/yuliangwang/Desktop/pbmc.markers.txt",sep = "\t")
LZ<-subset(pbmc,idents = "LZ")
DZ<-subset(pbmc,idents = "DZ")
Myc_cellcycle<-subset(pbmc,idents = "Myc_cellcyle")
Myc_plasma<-subset(pbmc,idents = "Myc_plasma")
Pre_Memory_B_cells<-subset(pbmc,idents = "Pre_Memory_B_cells")
cluster_PreMem.markers <- FindMarkers(pbmc, ident.1 = "Pre_Memory_B_cells")
write.table(cluster_PreMem.markers,file = "/Users/yuliangwang/Desktop/cluster9_preMeM.markers.txt",sep = "\t",col.names = TRUE,row.names = TRUE)
VlnPlot(pbmc,features = c("Tle3","Hhex","Cd38","Myc","Irf4","Arid5b"),pt.size = 0)
ClusterAverage<-AverageExpression(pbmc,assays = "RNA")
ClusterAverageexpression<-ClusterAverage[["RNA"]]
write.table(ClusterAverageexpression,file = "/Users/yuliangwang/Desktop/ClusterAverageexpression.txt",sep = "\t",col.names = TRUE,row.names = TRUE)
scaledata<-as.data.frame(pbmc@assays[["RNA"]]@scale.data)
write.table(scaledata,file = "/Users/yuliangwang/Desktop/scaledata.txt",sep = "\t",row.names = TRUE,col.names = TRUE)
countsdata<-as.data.frame(pbmc@assays[["RNA"]]@counts)
write.table(countsdata,file = "/Users/yuliangwang/Desktop/countsdata.txt",sep = "\t",row.names = TRUE,col.names = TRUE)

memoryB<-c("Tle3","Hhex","Cd38","Ccr6","Zeb2")
pbmc<-AddModuleScore(pbmc,features = rownames(cluster_PreMem.markers),name = "MemoryB")
library(dplyr)
a<-pbmc@meta.data
b<-select(a,starts_with("MemoryB"))
pbmc@meta.data$MemoryB<-apply(b,MARGIN = 1,mean)
FeaturePlot(pbmc,features = "MemoryB",reduction = "tsne",label = FALSE)+ scale_color_gradientn(colours = colorRampPalette(rev(brewer.pal(n = 7, name ="RdYlBu")))(10))
FeaturePlot(pbmc,features = "MemoryB",reduction = "tsne",label = FALSE,min.cutoff = 0)+ scale_color_gradientn(colours = colorRampPalette(rev(brewer.pal(n = 7, name ="RdYlBu")))(10))
